### ISSUE TITLE
ftMget jackson issue

### ISSUE THREAD

**Issue by autocorrectoff** [RediSearch/lettusearch#5] opened 2019-12-12 14:02 UTC
I try to perform multiget like so:
`Mono<List<Map<String, String>>> res = conn.ftMget("my_index", "my_index:C6009e1aa52dea00b0f320c46da7a99a9", "my_index:C632be3ebf9bf590272f36e7e8b65d005");`

Index is valid as are the doc ids. The exception is:

Type definition error: [collection type; class java.util.List, contains [map type; class java.util.Map, [simple type, class java.lang.String] -> [simple type, class java.lang.String]]]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Incompatible types: declared root type ([collection type; class java.util.List, contains [map type; class java.util.Map, [simple type, class java.lang.String] -> [simple type, class java.lang.String]]]) vs `java.util.LinkedHashMap`

It looks like a deserialization issue

**Comment by jruaux** [comment] 2019-12-27 12:41
Could you post the whole stack trace?

**Comment by autocorrectoff** [comment] 2019-12-27 15:45
2019-12-27 16:44:38.194 ERROR 32619 --- [lEventLoop-10-1] a.w.r.e.AbstractErrorWebExceptionHandler : [467c2af5]  500 Server Error for HTTP GET "/main/mget"

java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.util.List (java.util.LinkedHashMap and java.util.List are in module java.base of loader 'bootstrap')
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler io.node.lettusearchdemo.controllers.MainController#mget() [DispatcherHandler]
	|_ checkpoint ⇢ HTTP GET "/main/mget" [ExceptionHandlingWebHandler]
Stack trace:
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
		at io.lettuce.core.RedisPublisher$ImmediateSubscriber.onNext(RedisPublisher.java:888) ~[lettuce-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
		at io.lettuce.core.RedisPublisher$RedisSubscription.onNext(RedisPublisher.java:281) ~[lettuce-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
		at io.lettuce.core.output.StreamingOutput$Subscriber.onNext(StreamingOutput.java:64) ~[lettuce-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
		at com.redislabs.lettusearch.search.MapListOutput.complete(MapListOutput.java:79) ~[lettusearch-1.7.3.jar:na]
		at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:187) ~[lettuce-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
		at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:716) ~[lettuce-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
		at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:680) ~[lettuce-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
		at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:675) ~[lettuce-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
		at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:596) ~[lettuce-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
		at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:565) ~[lettuce-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
		at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[netty-transport-native-epoll-4.1.43.Final-linux-x86_64.jar:4.1.43.Final]
		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:502) ~[netty-transport-native-epoll-4.1.43.Final-linux-x86_64.jar:4.1.43.Final]
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-native-epoll-4.1.43.Final-linux-x86_64.jar:4.1.43.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
		at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

**Comment by jruaux** [comment] 2019-12-30 10:30
I'm not able to reproduce the issue. Could you paste the code you're using? Here is my test case:
`Mono<List<Map<String, String>>> mono = connection.reactive().ftMget(INDEX, "1836", "1837", "292929292");
mono.subscribe(list -> {
   Assert.assertEquals(3, list.size());
});`

**Comment by jruaux** [comment] 2019-12-30 11:01
Found the issue. It's fixed in 1.10.1. Thanks for reporting it!

**Closed** 2020-01-28 22:43 UTC
